### PR TITLE
feat: added update

### PR DESCRIPTION
**Pull request by cleeh**
In my project, secret key for token is saved in .env file.
So, it is necessary to periodically change the secret key for security purpose.

How to use it is as follows.
```
const dict = { SECRET_KEY: "NEW_SECRET_KEY" };
const options: ConfigOptions = { path: ".env.secret", export: true };
update(dict, options);
```

### CODE REVIEW

**Comment by pasha-bolokhov** [comment]
I think writing to `.env` is a bad idea. It is not a JSON file, and has a very loose structure, with comments, line breaks, quotation _etc_, which would be quite hard to keep during such updates

**Comment by rockatoo** [comment]
Thanks for the comment @pasha-bolokhov !
I agree with you in part. `.env` file has loose structure.

I think that it's also hard to read `.env` file if it's hart to write/update.
Because writing needs same rules as reading.
And updating should be carried out after reading.

`.env` file is also file like the `.json` file.
there is just rule some groups decided that `.env` file is should be readonly file.
And other groups may need write/update file.

I know that the author is skeptical about writing/updating `.env` file.
But if user don't want this feature, user can choose not to use it.

### there are two ways to block using writing/updating:
  - set `.env` file permission so make it readonly
  - add patch that user can block writing/updating `.env` file

**Comment by pasha-bolokhov** [comment]
> Thanks for the comment @pasha-bolokhov ! I agree with you in part. `.env` file has loose structure.
> 
> I think that it's also hard to read `.env` file if it's hart to write/update. Because writing needs same rules as reading. And updating should be carried out after reading.
> 
> `.env` file is also file like the `.json` file. there is just rule some groups decided that `.env` file is should be readonly file. And other groups may need write/update file.
> 
> I know that the author is skeptical about writing/updating `.env` file. But if user don't want this feature, user can choose not to use it.
> 
> ### there are two ways to block using writing/updating:
> * set `.env` file permission so make it readonly
> * add patch that user can block writing/updating `.env` file

I'm not the author of this package, just expressing my opinion…
You may be much better off using a `json` file if you want to easily read and write data in a pain–free mode…

**Comment by rockatoo** [comment]
> I'm not the author of this package, just expressing my opinion… You may be much better off using a `json` file if you want to easily read and write data in a pain–free mode…

Oh! you are right! I haven't thought about using other file format.
I'm ashamed that I insisted on using `.env` file format even if there are other good file format.

thanks for good idea!

**Pull request closed without merging**
