### PR TITLE
Fix escaping single quotes

### PR DESCRIPTION
**Pull request by gewoonwoutje**
Uses multi-line modifier on regex to match ^ and $

### CODE REVIEW

**Comment by pietvanzoen** [comment]
Thanks for the PR. Can you give me an example of a failing case? I'd like to add a test to cover it.

**Comment by gewoonwoutje** [comment]
The single quote test case failed on my device. (Windows device). The quotes were not escaped.

If you weren't having any issues, than this could be an incorrect fix🤔

**Comment by gewoonwoutje** [comment]
I think this fixes it because of the line endings.

**Comment by pietvanzoen** [comment]
Gotcha. Yeah I'm on MacOS and the build is linux. 

I'm gonna try adding windows to the build environment and see what happens there.

**Comment by pietvanzoen** [comment]
this fix makes the tests pass on your machine?

**Comment by pietvanzoen** [comment]
If so I'm happy to merge. Trying to test against windows but it's still in early access on travis and this build seems to be hanging: https://travis-ci.com/pietvanzoen/deno-dotenv/jobs/289618956

**Comment by gewoonwoutje** [comment]
Yes it fixes it, but I'm a bit surprised this is the only one that breaks... It's definitely the line ending.

**Comment by pietvanzoen** [comment]
Curious. Merged. I'll make a release. 

If travis windows ever works I'll try to setup a test for it.

**Comment by pietvanzoen** [comment]
Thanks again for the PRs!

**Comment by gewoonwoutje** [comment]
To make your TDD guts a little bit more happy, some images: 

Failing test: image

Changing CRLF to LF fixes it: image

My branch fixes it for CRLF image

**Comment by pietvanzoen** [comment]
haha! They are happy. Thanks! 😛

**Pull request merged**
